package presentation;

import factory.Factory;
import doctor.system.IDoctorDAO;
import doctor.system.NewDoctorDTO;
import javax.swing.JOptionPane;
import user.system.IUserDAO;
import user.system.NewUserDTO;

public class JFrameRegisterDoctor extends javax.swing.JFrame {

    private NewUserDTO userDTOAdmin;

    /**
     * Creates new form JFrameRegisterDoctor
     */
    public JFrameRegisterDoctor(NewUserDTO userDTOAdmin) {
        initComponents();
        this.userDTOAdmin = userDTOAdmin;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPanel = new javax.swing.JPanel();
        FondoAzul = new javax.swing.JPanel();
        Hospital_General = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNames = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtSeconName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnConfirm1 = new javax.swing.JButton();
        txtFirstName = new javax.swing.JTextField();
        txtMedicalCart = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        comboBox = new javax.swing.JComboBox<>();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FondoPanel.setBackground(new java.awt.Color(255, 255, 255));
        FondoPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoAzul.setBackground(new java.awt.Color(0, 153, 255));
        FondoAzul.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        FondoAzul.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Hospital_General.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Hospital_General.setText("General Hospital");
        FondoAzul.add(Hospital_General, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 39));

        FondoPanel.add(FondoAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Register Doctor");
        FondoPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        txtNames.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNames.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamesActionPerformed(evt);
            }
        });
        FondoPanel.add(txtNames, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 160, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setText("Names");
        FondoPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 110, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("First Last Name");
        FondoPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setText("Second Last Name");
        FondoPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        txtSeconName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtSeconName.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtSeconName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeconNameActionPerformed(evt);
            }
        });
        FondoPanel.add(txtSeconName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 110, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setText("Medicalcart");
        FondoPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        FondoPanel.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, -1));

        btnConfirm1.setText("Accept");
        btnConfirm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirm1ActionPerformed(evt);
            }
        });
        FondoPanel.add(btnConfirm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, -1, -1));

        txtFirstName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtFirstName.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        FondoPanel.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 110, -1));

        txtMedicalCart.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtMedicalCart.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtMedicalCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicalCartActionPerformed(evt);
            }
        });
        FondoPanel.add(txtMedicalCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 160, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setText("Password");
        FondoPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setText("User");
        FondoPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        txtUser.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtUser.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        FondoPanel.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 130, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setText("Specialization");
        FondoPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, -1));

        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {" NONE",
            "SURGERY",
            "PSYCHIATRY",
            "ANESTHIOLOGY",
            "FAMILY",
            "CARDIOLOGY",
            "PEDIATRIC"}));
comboBox.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        comboBoxActionPerformed(evt);
    }
    });
    FondoPanel.add(comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 120, -1));
    FondoPanel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 360, 130, -1));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(FondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(FondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamesActionPerformed

    private void txtSeconNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeconNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeconNameActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:

        JFrameAdministrator frameAdministrator = new JFrameAdministrator(userDTOAdmin.getUser(), userDTOAdmin.getPassword());
        frameAdministrator.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnConfirm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirm1ActionPerformed
        // TODO add your handling code here:

        String names = txtNames.getText();
        String firstName = txtFirstName.getText();
        String secondName = txtSeconName.getText();
        String medicalCart = txtMedicalCart.getText();
        String specialization = (String) comboBox.getSelectedItem();
        String user = txtUser.getText();
        String password = txtPassword.getText();

        if (names.isEmpty() || firstName.isEmpty() || secondName.isEmpty()
                || medicalCart.isEmpty() || user.isEmpty() || password.isEmpty()) {

            JOptionPane.showMessageDialog(null, "Favor de llenar todos los campos", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        if (!names.matches("[a-zA-ZñÑáéíóúÁÉÍÓÚ\\s]+") || !firstName.matches("[a-zA-ZñÑáéíóúÁÉÍÓÚ]+") || !secondName.matches("[a-zA-ZñÑáéíóúÁÉÍÓÚ]+")) {
            JOptionPane.showMessageDialog(null, "Names can only contain leters", "Error", JOptionPane.INFORMATION_MESSAGE);
        } else {

            NewDoctorDTO doctorDTO = new NewDoctorDTO(
                    names,
                    firstName,
                    secondName,
                    specialization,
                    medicalCart);

            doctorDTO.setSpecialization(specialization);

            IDoctorDAO doctorDAO = Factory.getDoctorDAO();

            IUserDAO userDAO = Factory.getUserDAO();

            if (userDAO.userExist(user)) {

                JOptionPane.showMessageDialog(this, "The username is already in use");

            } else {

                if (doctorDAO.searchByMedicart(doctorDTO.getMedicalCart()) == null) {
                    doctorDAO.registerDoctor(doctorDTO);
                    NewUserDTO userDTO = new NewUserDTO(user, password, doctorDTO);
                    userDAO.registerDoctorUser(doctorDTO, userDTO);
                    JFrameAdministrator frameAdministrator = new JFrameAdministrator(userDTOAdmin.getUser(), userDTOAdmin.getPassword());
                    frameAdministrator.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "The medicalCart is already in use");
                }

            }

        }

    }//GEN-LAST:event_btnConfirm1ActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtMedicalCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicalCartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicalCartActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed

    }//GEN-LAST:event_comboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoAzul;
    private javax.swing.JPanel FondoPanel;
    private javax.swing.JLabel Hospital_General;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm1;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtMedicalCart;
    private javax.swing.JTextField txtNames;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSeconName;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
