package presentation;

import com.toedter.calendar.JDateChooser;
import factory.Factory;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import patient.system.IPatientDAO;
import patient.system.NewPatientDTO;
import user.system.IUserDAO;
import user.system.NewUserDTO;

public class JFrameRegisterPatient extends javax.swing.JFrame {

    private NewUserDTO userDTO;
    private NewUserDTO userDTOAdmin;
    private JDateChooser dateChooser;

    /**
     * Creates new form RegistroPaciente
     */
    public JFrameRegisterPatient(NewUserDTO userDTO) {
        initComponents();
        txtOther.setEditable(false);
        this.userDTO = userDTO;
        dateChooser();
        this.setTitle("Registro Paciente");
    }

    public JFrameRegisterPatient(NewUserDTO userDTO, NewUserDTO userDTOAdmin) {

        initComponents();
        txtOther.setEditable(false);
        this.userDTO = userDTO;
        dateChooser();
        this.setTitle("Registro Paciente");
        this.userDTOAdmin = userDTOAdmin;

    }

    public void dateChooser() {

        this.dateChooser = new JDateChooser();
        this.dateChooser.setBounds(lblDate.getBounds());
        this.add(dateChooser);

    }

    public void limitarFecha() {
        Calendar fechaMinima = Calendar.getInstance();
        fechaMinima.set(Calendar.YEAR, -18);
        Date minimo = fechaMinima.getTime();
        Calendar fechaMaxima = Calendar.getInstance();
        fechaMaxima.add(Calendar.DATE, -1);
        Date maximo = fechaMaxima.getTime();
        dateChooser.setSelectableDateRange(minimo, maximo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPanel = new javax.swing.JPanel();
        Iniciar_Sesion = new javax.swing.JLabel();
        FondoAzul = new javax.swing.JPanel();
        Hospital_General = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        Usuario = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtCurp = new javax.swing.JTextField();
        Usuario3 = new javax.swing.JLabel();
        Usuario4 = new javax.swing.JLabel();
        txtColony = new javax.swing.JTextField();
        Usuario5 = new javax.swing.JLabel();
        txtStreet = new javax.swing.JTextField();
        Usuario7 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        Usuario6 = new javax.swing.JLabel();
        txtSecurityNumber = new javax.swing.JTextField();
        Usuario8 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        FondoGenero = new javax.swing.JPanel();
        Usuario1 = new javax.swing.JLabel();
        cbxMale = new javax.swing.JCheckBox();
        cbxFamele = new javax.swing.JCheckBox();
        Usuario11 = new javax.swing.JLabel();
        txtOther = new javax.swing.JTextField();
        cbxOther = new javax.swing.JCheckBox();
        txtZipCode = new javax.swing.JTextField();
        Usuario9 = new javax.swing.JLabel();
        txtSecondName = new javax.swing.JTextField();
        Usuario12 = new javax.swing.JLabel();
        Usuario13 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FondoPanel.setBackground(new java.awt.Color(255, 255, 255));
        FondoPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Iniciar_Sesion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Iniciar_Sesion.setText("Register Patient");

        FondoAzul.setBackground(new java.awt.Color(0, 153, 255));
        FondoAzul.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Hospital_General.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        Hospital_General.setText("Hospital General");

        javax.swing.GroupLayout FondoAzulLayout = new javax.swing.GroupLayout(FondoAzul);
        FondoAzul.setLayout(FondoAzulLayout);
        FondoAzulLayout.setHorizontalGroup(
            FondoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoAzulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Hospital_General, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(596, Short.MAX_VALUE))
        );
        FondoAzulLayout.setVerticalGroup(
            FondoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoAzulLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Hospital_General, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        Usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Usuario.setText("Names");

        Usuario3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Usuario3.setText("CURP");

        Usuario4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Usuario4.setText("First Last Name");

        Usuario5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Usuario5.setText("Colony");

        txtStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStreetActionPerformed(evt);
            }
        });

        Usuario7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Usuario7.setText("Street");

        Usuario6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Usuario6.setText("Phone Number");

        Usuario8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Usuario8.setText("Insurance Number");

        btnAceptar.setBackground(new java.awt.Color(0, 0, 0));
        btnAceptar.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Accept");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        FondoGenero.setBackground(new java.awt.Color(255, 255, 255));
        FondoGenero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        Usuario1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Usuario1.setText("Sex");

        cbxMale.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        cbxMale.setText("Male");
        cbxMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMaleActionPerformed(evt);
            }
        });

        cbxFamele.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        cbxFamele.setText("Female");
        cbxFamele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFameleActionPerformed(evt);
            }
        });

        Usuario11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Usuario11.setText("Other");

        cbxOther.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        cbxOther.setText("Other");
        cbxOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxOtherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondoGeneroLayout = new javax.swing.GroupLayout(FondoGenero);
        FondoGenero.setLayout(FondoGeneroLayout);
        FondoGeneroLayout.setHorizontalGroup(
            FondoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoGeneroLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(FondoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Usuario1)
                    .addGroup(FondoGeneroLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(cbxMale)
                        .addGap(34, 34, 34)
                        .addComponent(cbxFamele)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(cbxOther)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FondoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Usuario11)
                    .addComponent(txtOther, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        FondoGeneroLayout.setVerticalGroup(
            FondoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoGeneroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FondoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Usuario11)
                    .addComponent(Usuario1))
                .addGap(1, 1, 1)
                .addGroup(FondoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxMale)
                        .addComponent(cbxFamele))
                    .addGroup(FondoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtOther, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxOther)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        Usuario9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Usuario9.setText("Zipcode");

        Usuario12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Usuario12.setText("Birth Date");

        Usuario13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Usuario13.setText("Second Last Name");

        javax.swing.GroupLayout FondoPanelLayout = new javax.swing.GroupLayout(FondoPanel);
        FondoPanel.setLayout(FondoPanelLayout);
        FondoPanelLayout.setHorizontalGroup(
            FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoPanelLayout.createSequentialGroup()
                .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FondoAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FondoPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(Usuario)
                        .addGap(233, 233, 233)
                        .addComponent(Usuario4)
                        .addGap(112, 112, 112)
                        .addComponent(Usuario13)
                        .addGap(71, 71, 71)
                        .addComponent(Usuario12))
                    .addGroup(FondoPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(FondoGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Usuario8)
                            .addComponent(txtSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(FondoPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(Usuario6)
                        .addGap(258, 258, 258)
                        .addComponent(Usuario3))
                    .addGroup(FondoPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(txtCurp, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FondoPanelLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FondoPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(txtSecondName, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FondoPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Usuario9))
                        .addGap(40, 40, 40)
                        .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FondoPanelLayout.createSequentialGroup()
                                .addComponent(Usuario5)
                                .addGap(193, 193, 193)
                                .addComponent(Usuario7))
                            .addGroup(FondoPanelLayout.createSequentialGroup()
                                .addComponent(txtColony, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(FondoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Iniciar_Sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        FondoPanelLayout.setVerticalGroup(
            FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoPanelLayout.createSequentialGroup()
                .addComponent(FondoAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Iniciar_Sesion)
                .addGap(21, 21, 21)
                .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Usuario13)
                    .addComponent(Usuario12)
                    .addGroup(FondoPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Usuario)
                            .addComponent(Usuario4))))
                .addGap(1, 1, 1)
                .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSecondName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FondoGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FondoPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Usuario8)
                        .addGap(1, 1, 1)
                        .addComponent(txtSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Usuario9)
                        .addComponent(Usuario5))
                    .addComponent(Usuario7))
                .addGap(1, 1, 1)
                .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColony, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Usuario6)
                    .addComponent(Usuario3))
                .addGroup(FondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtCurp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FondoPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:

        String names = txtName.getText();
        String firstName = txtFirstName.getText();
        String secondName = txtSecondName.getText();
        String colony = txtColony.getText();
        String zipCodeS = txtZipCode.getText();
        String curp = txtCurp.getText();
        String phone = txtPhone.getText();
        String socialNumber = txtSecurityNumber.getText();
        String street = txtStreet.getText();
        Calendar birthDate = dateChooser.getCalendar();
        String sex = "";
        if (cbxMale.isSelected()) {
            sex = "M";
        } else if (cbxFamele.isSelected()) {
            sex = "F";
        } else if (cbxOther.isSelected()) {
            sex = txtOther.getText();
        } else {
            sex = "";
        }

        if (names.isEmpty() || firstName.isEmpty() || secondName.isEmpty() || colony.isEmpty()
                || zipCodeS.isEmpty() || curp.isEmpty() || phone.isEmpty() || socialNumber.isEmpty()
                || street.isEmpty() || sex.isEmpty() || birthDate == null) {
            JOptionPane.showMessageDialog(null, "Favor de llenar todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if (!names.matches("[a-zA-ZñÑáéíóúÁÉÍÓÚ\\s]+") || !firstName.matches("[a-zA-ZñÑáéíóúÁÉÍÓÚ]+") || !secondName.matches("[a-zA-ZñÑáéíóúÁÉÍÓÚ]+")) {
            JOptionPane.showMessageDialog(null, "Names can only contain leters", "Error", JOptionPane.INFORMATION_MESSAGE);
        } else {

            int zipCode = Integer.parseInt(zipCodeS);
            NewPatientDTO newPatientDTO = new NewPatientDTO(
                    names, firstName, secondName, birthDate, sex, curp, socialNumber, phone, street, colony, zipCode
            );

            try {
                //Creamos paciente nuevo
                IPatientDAO patientSystem = Factory.getPatientDAO();
                patientSystem.registerPatient(newPatientDTO);

                IUserDAO userSystem = Factory.getUserDAO();
                userDTO.setPatientDTO(newPatientDTO);
                userSystem.registerUser(userDTO);

            } catch (Exception ex) {
                Logger.getLogger(JFrameRegisterPatient.class.getName()).log(Level.SEVERE, "Error al persistir", ex);
            }

            if (userDTOAdmin == null) {
                JFrameLogin frameLogin = new JFrameLogin();
                frameLogin.setVisible(true);
                this.dispose();
            } else {
                JFrameAdministrator admin = new JFrameAdministrator(userDTOAdmin.getUser(), userDTOAdmin.getPassword());
                admin.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void cbxMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMaleActionPerformed
        // TODO add your handling code here:
        cbxFamele.setSelected(false);
        cbxOther.setSelected(false);
        txtOther.setEditable(false);
    }//GEN-LAST:event_cbxMaleActionPerformed

    private void cbxFameleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFameleActionPerformed
        // TODO add your handling code here:

        cbxMale.setSelected(false);
        txtOther.setEditable(false);
        cbxOther.setSelected(false);

    }//GEN-LAST:event_cbxFameleActionPerformed

    private void cbxOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxOtherActionPerformed
        // TODO add your handling code here:
        cbxMale.setSelected(false);
        cbxFamele.setSelected(false);
        txtOther.setEditable(true);
    }//GEN-LAST:event_cbxOtherActionPerformed

    private void txtStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStreetActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//     txtFirstNamer-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JFRegisterPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JFRegisterPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JFRegisterPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JFRegisterPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JFRegisterPatient().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoAzul;
    private javax.swing.JPanel FondoGenero;
    private javax.swing.JPanel FondoPanel;
    private javax.swing.JLabel Hospital_General;
    private javax.swing.JLabel Iniciar_Sesion;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel Usuario1;
    private javax.swing.JLabel Usuario11;
    private javax.swing.JLabel Usuario12;
    private javax.swing.JLabel Usuario13;
    private javax.swing.JLabel Usuario3;
    private javax.swing.JLabel Usuario4;
    private javax.swing.JLabel Usuario5;
    private javax.swing.JLabel Usuario6;
    private javax.swing.JLabel Usuario7;
    private javax.swing.JLabel Usuario8;
    private javax.swing.JLabel Usuario9;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JCheckBox cbxFamele;
    private javax.swing.JCheckBox cbxMale;
    private javax.swing.JCheckBox cbxOther;
    private javax.swing.JLabel lblDate;
    private javax.swing.JTextField txtColony;
    private javax.swing.JTextField txtCurp;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOther;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSecondName;
    private javax.swing.JTextField txtSecurityNumber;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables
}
